/**
 * A page for the e2e build's scanner: a small synthetic ID card (the PDF
 * tests' card.jpg, 300 × 190 px, no metadata), as base64. The e2e build
 * runs on an emulator with no camera worth scanning with.
 */
export const FIXTURE_PAGE_BASE64 =
  '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAoHBwgHBgoICAgLCgoLDhgQDg0NDh0VFhEYIx8lJCIfIiEmKzcvJik0KSEiMEExNDk7' +
  'Pj4+JS5ESUM8SDc9Pjv/2wBDAQoLCw4NDhwQEBw7KCIoOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7' +
  'Ozs7Ozs7Ozv/wAARCAC+ASwDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUF' +
  'BAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVW' +
  'V1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi' +
  '4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAEC' +
  'AxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVm' +
  'Z2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq' +
  '8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD1eiiigzCiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKK' +
  'KACiiigAooooAKKKKACiiigAooooAKKKKACiiigD58oooqjywooooAKKKKACiiigAooooAK0PD3/ACMmmf8AX5F/6GKz60PD3/Iy' +
  'aZ/1+Rf+higcd0e50UUVJ6YUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQB8+UUUVR5YUUUU' +
  'AFFFFABRRRQAUUUUAFaHh7/kZNM/6/Iv/QxWfWh4e/5GTTP+vyL/ANDFA47o9zoooqT0wooooAKKKKACiiigAooooAKKKKACiiig' +
  'AooooAKKKKACiiigAooooAKKKKACiiigD58oooqjywooooAKKKKACiiigAooooAK0PD3/IyaZ/1+Rf8AoYrPrQ8Pf8jJpn/X5F/6' +
  'GKBx3R7nRRRUnphRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFAHz5RRRVHlhRRRQAUUUUAFF' +
  'FFABRRRQAVoeHv8AkZNM/wCvyL/0MVn1oeHv+Rk0z/r8i/8AQxQOO6Pc6KKKk9MKKKKACiiigAooooAKKKKACiiigAooooAKKKKA' +
  'CiiigAooooAKKKKACiiigAooooA+fKKKKo8sKKKKACiiigAooooAKKKKACtDw9/yMmmf9fkX/oYrPrQ8Pf8AIyaZ/wBfkX/oYoHH' +
  'dHudFFFSemFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAfPlFFFUeWFFFFABRRRQAUUUUAF' +
  'FFFABWh4e/5GTTP+vyL/ANDFZ9aHh7/kZNM/6/Iv/QxQOO6Pc6KKKk9MKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAo' +
  'oooAKKKKACiiigAooooA+fKKKKo8sKKKKACiiigAooooAKKKKACtDw9/yMmmf9fkX/oYrPrQ8Pf8jJpn/X5F/wChigcd0e50UUVJ' +
  '6YUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQB8+UUUVR5YUUUUAFFFFABRRRQAUUUUAFaHh' +
  '7/kZNM/6/Iv/AEMVn1oeHv8AkZNM/wCvyL/0MUDjuj3OiiipPTCiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACi' +
  'iigAooooAKKKKAPDP+Ee1v8A6A9//wCAz/4Uf8I9rf8A0B7/AP8AAZ/8K9zop3Ob6uu54Z/wj2t/9Ae//wDAZ/8ACj/hHtb/AOgP' +
  'f/8AgM/+Fe50UXD6uu54Z/wj2t/9Ae//APAZ/wDCj/hHtb/6A9//AOAz/wCFe50UXD6uu54Z/wAI9rf/AEB7/wD8Bn/wo/4R7W/+' +
  'gPf/APgM/wDhXudFFw+rrueGf8I9rf8A0B7/AP8AAZ/8KP8AhHtb/wCgPf8A/gM/+Fe50UXD6uu54Z/wj2t/9Ae//wDAZ/8ACr+h' +
  '6Hq8Ov6dLLpV6kaXUTMzW7gKA4yScdK9koouNUEnuFFFFI6AooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAoooo' +
  'AKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKK' +
  'KACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACi' +
  'iigAooooA//Z';
